openapi: 3.0.0
info:
  description: Kafka Connect REST API https://docs.confluent.io/platform/current/connect/references/restapi.html
  title: Kafka Connect REST API
  version: 0.1.9
servers:
- url: /
paths:
  /:
    get:
      operationId: getClusterInfo
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetClusterInfoResponse'
          description: OK
      summary: Top-level (root) request that gets the version of the Connect worker
        that serves the REST request, the git commit ID of the source code, and the
        Kafka cluster ID that the worker is connected to.
  /connectors:
    get:
      operationId: listConnectors
      parameters:
      - description: Retrieves additional state/configuration information for each
          of the connectors returned in the API call.
        explode: true
        in: query
        name: expand
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListConnectorsResponse'
          description: OK
      summary: Get a list of active connectors.
    post:
      operationId: createConnector
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateConnectorRequest'
        description: New connector request body
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateConnectorResponse'
          description: OK
      summary: Create a new connector, returning the current connector info if successful.
        Return 409 (Conflict) if rebalance is in process, or if the connector already
        exists.
  /connectors/{name}:
    delete:
      operationId: deleteConnector
      parameters:
      - description: Name of the connector.
        explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "204":
          description: No Content
        "409":
          description: Rebalance in progress
      summary: Delete a connector, halting all tasks and deleting its configuration.
    get:
      operationId: getConnector
      parameters:
      - description: Name of the connector.
        explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetConnectorResponse'
          description: OK
      summary: Get information about the connector.
  /connectors/{name}/status:
    get:
      operationId: getConnectorStatus
      parameters:
      - description: Name of the created connector.
        explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: OK
      summary: |
        Gets the current status of the connector, including:
        * whether it is running or restarting, or if it has failed or paused
        * which worker it is assigned to
        * error information if it has failed
        * the state of all its tasks
  /connectors/{name}/restart:
    post:
      operationId: restartConnector
      parameters:
      - description: Name of the connector.
        explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      - description: Specifies whether to restart the connector instance and task
          instances (includeTasks=true) or just the connector instance (includeTasks=false).
        explode: true
        in: query
        name: includeTasks
        required: false
        schema:
          type: boolean
        style: form
      - description: Specifies whether to restart just the instances with a FAILED
          status (onlyFailed=true) or all instances (onlyFailed=false).
        explode: true
        in: query
        name: onlyFailed
        required: false
        schema:
          type: boolean
        style: form
      responses:
        "200":
          description: OK
        "202":
          content:
            application/json:
              schema:
                type: object
          description: Accepted
        "204":
          description: No Content
        "404":
          description: Not Found
        "409":
          description: Rebalance in progress
        "500":
          description: Internal Server Error
      summary: Restart the connector. You may use the following query parameters to
        restart any combination of the Connector and/or Task instances for the connector.
  /connectors/{name}/pause:
    put:
      operationId: pauseConnector
      parameters:
      - description: Name of the connector to pause.
        explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "202":
          content:
            application/json:
              schema:
                type: object
          description: Accepted
        "500":
          description: Internal Server Error
      summary: Pause the connector and its tasks, which stops message processing until
        the connector is resumed. This call asynchronous and the tasks will not transition
        to PAUSED state at the same time.
  /connectors/{name}/resume:
    put:
      operationId: resumeConnector
      parameters:
      - description: Name of the connector to resume.
        explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "202":
          content:
            application/json:
              schema:
                type: object
          description: Accepted
        "500":
          description: Internal Server Error
      summary: Resume a paused connector or do nothing if the connector is not paused.
        This call asynchronous and the tasks will not transition to RUNNING state
        at the same time.
components:
  parameters:
    ConnectorNameParameter:
      description: Name of the connector.
      explode: false
      in: path
      name: name
      required: true
      schema:
        type: string
      style: simple
  schemas:
    GetClusterInfoResponse:
      example:
        kafka_cluster_id: kafka_cluster_id
        commit: commit
        version: version
      properties:
        version:
          description: Connect worker version.
          type: string
        commit:
          description: git commit ID.
          type: string
        kafka_cluster_id:
          description: Kafka cluster ID.
          type: string
      type: object
    CreateConnectorRequest:
      example:
        name: name
        config: '{}'
      properties:
        name:
          description: Name of the connector to create
          type: string
        config:
          description: Configuration parameters for the connector. All values should
            be strings.
          type: object
      type: object
    CreateConnectorResponse:
      example:
        name: name
        config: '{}'
        tasks:
        - task: 0.8008281904610115
          connector: connector
        - task: 0.8008281904610115
          connector: connector
      properties:
        name:
          description: Name of the created connector
          type: string
        config:
          description: Configuration parameters for the connector.
          type: object
        tasks:
          description: Lits of active tasks generated by the connector.
          items:
            $ref: '#/components/schemas/CreateConnectorResponse_tasks'
          type: array
      type: object
    ListConnectorsResponse:
      additionalProperties: true
      description: List of connectors.
      type: object
    GetConnectorResponse:
      example:
        name: name
        config: '{}'
        tasks:
        - task: 0.8008281904610115
          connector: connector
        - task: 0.8008281904610115
          connector: connector
      properties:
        name:
          description: Name of the created connector.
          type: string
        config:
          description: Configuration parameters for the connector.
          type: object
        tasks:
          description: List of active tasks generated by the connector.
          items:
            $ref: '#/components/schemas/CreateConnectorResponse_tasks'
          type: array
      type: object
    inline_response_200_connector:
      description: Connector status.
      example:
        state: state
        worker_id: worker_id
      properties:
        state:
          description: State of the connector.
          type: string
        worker_id:
          description: ID of the worker running the connector.
          type: string
      type: object
    inline_response_200_tasks:
      example:
        trace: trace
        id: 0.8008281904610115
        state: state
        worker_id: worker_id
      properties:
        id:
          description: ID of the task.
          type: number
        state:
          description: Current state of the task.
          type: string
        worker_id:
          description: ID of the worker running the task.
          type: string
        trace:
          description: Stack trace information if the task has failed.
          type: string
      type: object
    inline_response_200:
      example:
        connector:
          state: state
          worker_id: worker_id
        name: name
        tasks:
        - trace: trace
          id: 0.8008281904610115
          state: state
          worker_id: worker_id
        - trace: trace
          id: 0.8008281904610115
          state: state
          worker_id: worker_id
      properties:
        name:
          description: Name of the connector.
          type: string
        connector:
          $ref: '#/components/schemas/inline_response_200_connector'
        tasks:
          description: List of task status for the connector.
          items:
            $ref: '#/components/schemas/inline_response_200_tasks'
          type: array
      type: object
    CreateConnectorResponse_tasks:
      example:
        task: 0.8008281904610115
        connector: connector
      properties:
        connector:
          description: The name of the connector the task belongs to.
          type: string
        task:
          description: Task ID within the connector.
          type: number
      type: object
